version: '2'

services:
  ui:
    image: grafana/grafana
    restart: always
    ports:
      - "8081:3000"
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=secret"

  db:
    image: influxdb
    restart: always
    ports:
      - "8083:8083"
      - "8086:8086"
networks:
  default: